name: Environment Deployment

on:
  push:
    branches:
      - development
      - staging
      - production

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.select-env.outputs.name }}
    steps:
      - name: Select Environment Based on Branch
        id: select-env
        run: |
          if [ "${{ github.ref_ref }}" = "refs/heads/production" ]; then
            echo "name=production" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_ref }}" = "refs/heads/staging" ]; then
            echo "name=staging" >> $GITHUB_OUTPUT
          else
            echo "name=development" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: set-env
    runs-on: ubuntu-latest
    environment: ${{ needs.set-env.outputs.target_env }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate Build Process
        run: |
          echo "Собираем проект для ветки ${{ github.ref_name }}..."
          echo "Используем настройки для среды: ${{ needs.set-env.outputs.target_env }}"

      - name: Simulate Deployment
        run: |
          echo " Развертывание успешно запущено!"
          echo "Проект отправлен на адрес: ${{ vars.ENV_SITE_URL }}"
          echo "Статус: Успешно развернуто в ${{ needs.set-env.outputs.target_env }}